const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Vault,parseNote}=require('../src/vault.cjs');
const {listPlaces,savePlace,readPlace,updateLocation,setupPlaces,FOLDER}=require('../src/places.cjs');
const {createWorkspace}=require('../src/workspace.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'orb-places-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const created=createWorkspace(path.join(root,'vault'));return new Vault(created.vaultPath,path.join(root,'state'));}
test('starter contains empty Places, complete template, Base views and navigation',t=>{const v=fixture(t);assert.equal(listPlaces(v).places.length,0);assert.equal(listPlaces(v).setup,false);assert.equal(parseNote(v.read('99. System/99.1 Templates/10. Place Template.md').content).data.category,'Uncategorized');const base=fs.readFileSync(v.resolve('6. Life Admin/Places.base',{note:false}),'utf8');for(const name of ['All','By category','With coordinates'])assert.ok(base.includes(name));assert.match(v.read('0. Home/Home.md').content,/Places/);});
test('save preserves zero and unknown coordinates, makes complete YAML, deduplicates and supports undo',t=>{const v=fixture(t),input={name:'Café & Books',category:'Book café',location:'A fictional address',latitude:0,longitude:0,notes:'Quiet upstairs.'};const result=savePlace(v,input),p=readPlace(v,result.path);assert.equal(p.latitude,0);assert.equal(p.longitude,0);assert.equal(p.category,'Book café');assert.match(p.body,/Quiet upstairs/);assert.equal(savePlace(v,input).duplicate,true);assert.equal(listPlaces(v).places.length,1);v.undo(result.change_id);assert.equal(listPlaces(v).places.length,0);const blank=savePlace(v,{name:'Unknown location'}),data=parseNote(v.read(blank.path).content).data;assert.equal(data.latitude,null);assert.equal(data.longitude,null);assert.equal(data.category,'Uncategorized');});
test('invalid coordinates and dangerous websites are rejected; same-name branches never overwrite',t=>{const v=fixture(t);for(const bad of [NaN,Infinity,91,'51'])assert.throws(()=>savePlace(v,{name:'Bad',latitude:bad}),/latitude/);assert.throws(()=>savePlace(v,{name:'Bad',website:'javascript:alert(1)'}),/HTTP/);savePlace(v,{name:'Same name',location:'North'});assert.throws(()=>savePlace(v,{name:'Same name',location:'South'}),/different place/);assert.equal(listPlaces(v).places[0].location,'North');});
test('only typed place notes in Places are read and malformed notes do not hide valid places',t=>{const v=fixture(t);savePlace(v,{name:'Good',location:'Here'});fs.writeFileSync(v.resolve(FOLDER+'/Other.md',{missing:true}),'---\ntype: task\n---\n');fs.writeFileSync(v.resolve(FOLDER+'/Broken.md',{missing:true}),'---\ntype: [broken\n---\n');fs.writeFileSync(v.resolve(FOLDER+'/Bad coordinates.md',{missing:true}),'---\ntype: place\nlatitude: 100\nlongitude: 2\n---\n');const result=listPlaces(v);assert.equal(result.places.length,2);assert.ok(result.warnings.length>=2);assert.equal(result.places.find(p=>p.name==='Bad coordinates').latitude,null);assert.equal(listPlaces(v,{query:'Good'}).places.length,1);assert.throws(()=>readPlace(v,'0. Home/Home.md'),/Places folder/);});
test('location edits preserve custom YAML and body, reject stale versions and undo',t=>{const v=fixture(t),saved=savePlace(v,{name:'Park',location:'Here'});const file=v.resolve(saved.path);fs.appendFileSync(file,'\nPersonal observation.\n');let content=fs.readFileSync(file,'utf8').replace('type: place','type: place\ncustom: keep');fs.writeFileSync(file,content);const before=readPlace(v,saved.path);assert.throws(()=>updateLocation(v,{path:saved.path,version:saved.version,latitude:51,longitude:0}),/changed/);const result=updateLocation(v,{path:saved.path,version:before.version,latitude:51,longitude:0});const after=v.read(saved.path);assert.equal(parseNote(after.content).data.custom,'keep');assert.match(after.content,/Personal observation/);v.undo(result.change_id);assert.equal(v.read(saved.path).content,content);});
test('setup is additive and rejects symlink escapes',t=>{const v=fixture(t);const guide=v.resolve('6. Life Admin/Places.md');fs.writeFileSync(guide,'Custom directory');fs.unlinkSync(v.resolve('6. Life Admin/Places.base',{note:false}));assert.deepEqual(setupPlaces(v).missing,['6. Life Admin/Places.base']);assert.equal(setupPlaces(v,{apply:true}).created.length,1);assert.equal(fs.readFileSync(guide,'utf8'),'Custom directory');assert.equal(setupPlaces(v,{apply:true}).created.length,0);fs.rmdirSync(v.resolve(FOLDER,{note:false}));fs.symlinkSync(os.tmpdir(),path.join(v.root,FOLDER));assert.throws(()=>savePlace(v,{name:'Escape'}),/Symbolic/);assert.throws(()=>listPlaces(v),/Symbolic/);});
