const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Vault}=require('../src/vault.cjs'),{savePlace}=require('../src/places.cjs');
const {createWorkspace}=require('../src/workspace.cjs');
const {createPlacesService,readPlacesSettings,withPlacesSettings,placesKey,directionsURL,persistedPlaces,forModel}=require('../src/places-service.cjs');
const {ChatStore}=require('../src/chats.cjs');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orb-places-service-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const v=new Vault(createWorkspace(path.join(dir,'vault')).vaultPath,path.join(dir,'state'));return {v,dir};}
const origin={name:'Example area',location:'Example area',latitude:51.5,longitude:-.1};
const café={name:'Example café',category:'Café',location:'Example road',latitude:51.501,longitude:-.101,website:'',source:'geoapify'};
function service(v,extra={}){return createPlacesService({getVault:()=>v,getConfig:()=>({places:{encryptedKey:'fixture'}}),provider:{geocode:async()=>[origin],search:async()=>[{...café}],walkingRoute:async()=>({seconds:360})},...extra});}
test('unknown/ambiguous origins request selection, quietness is not invented and routing is sourced',async t=>{const {v}=fixture(t),s=service(v);const missing=await s.command({action:'search',query:'quiet coffee shop'});assert.equal(missing.state,'origin');assert.equal(missing.results.length,0);const result=await s.command({action:'search',query:'quiet coffee shop',area:'Example area'});assert.equal(result.results[0].walkingSeconds,360);assert.equal(result.results[0].evidence,'Quietness not verified');assert.equal(forModel(result).results[0].walkingSeconds,360);const ambiguous=service(v,{provider:{geocode:async()=>[origin,{...origin,name:'Other'}]}});assert.equal((await ambiguous.command({action:'search',query:'coffee',area:'Example'})).choices.length,2);});
test('saved/provider duplicates merge, geocoding is transient, failures produce honest partial results',async t=>{const {v}=fixture(t);const note=savePlace(v,{...café,notes:'Not quiet on Saturdays.'});const s=service(v),result=await s.command({action:'search',query:'quiet cafe',area:'Example'});assert.equal(result.results.length,1);assert.match(result.results[0].evidence,/Not quiet on Saturdays/);assert.equal(result.results[0].path,note.path);const failed=service(v,{provider:{geocode:async()=>[origin],search:async()=>{throw new Error('quota reached');},walkingRoute:async()=>{throw new Error('no route');}}});const partial=await failed.command({action:'search',query:'cafe',area:'Example'});assert.equal(partial.results[0].walkingSeconds,null);assert.match(partial.warnings.join(' '),/quota/);});
test('save uses backend result identity, supports retry and rejects expired/other-vault results',async t=>{const {v}=fixture(t);let now=100,changes=0;const s=service(v,{now:()=>now,onChange:()=>changes++}),result=await s.command({action:'search',query:'cafe',area:'Example'});const saved=await s.command({action:'save',id:result.results[0].id});assert.ok(saved.change_id);assert.equal((await s.command({action:'save',id:result.results[0].id})).duplicate,true);assert.equal(changes,1);now+=31*60000;await assert.rejects(s.command({action:'save',id:result.results[0].id}),/expired/);s.clear();await assert.rejects(s.command({action:'save',id:result.results[0].id}),/expired/);});
test('settings preserve unrelated values, encrypt credentials and never return them publicly',()=>{const safe={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from('enc:'+s),decryptString:b=>b.toString().slice(4)},config={weather:{units:'metric'},appearance:{orbColour:'#123456'}};const next=withPlacesSettings(config,{key:'fixture-secret',defaultArea:'Soho',directionsApp:'google'},safe);assert.deepEqual(next.weather,config.weather);assert.equal(placesKey(next,safe),'fixture-secret');assert.equal(JSON.stringify(readPlacesSettings(next)).includes('secret'),false);assert.equal(readPlacesSettings(withPlacesSettings(next,{disconnect:true},safe)).configured,false);assert.throws(()=>withPlacesSettings(next,{directionsApp:'evil'},safe));});
test('directions safely encode names and walking mode; persisted visuals strip device origins and handles',async t=>{const {v,dir}=fixture(t),s=service(v),view=await s.command({action:'search',query:'cafe',area:'Example'});for(const app of ['google','apple']){const u=new URL(directionsURL(café,app,origin));assert.equal(u.searchParams.get(app==='google'?'travelmode':'dirflg'),app==='google'?'walking':'w');assert.ok(u.searchParams.get(app==='google'?'destination':'daddr').includes('51.501'));}assert.throws(()=>directionsURL({name:'Only a name'}),/address/);assert.throws(()=>directionsURL(café,'evil'));const clean=persistedPlaces(view);assert.equal(clean.origin,undefined);assert.equal(clean.originId,undefined);assert.equal(clean.results[0].id,undefined);assert.equal(clean.historical,true);const chats=new ChatStore(path.join(dir,'chats.json')),chat=chats.open(require('node:crypto').randomUUID(),'Coffee');chats.append(chat.id,{role:'assistant',text:'Here are places.',visual:view});assert.equal(chats.get(chat.id).messages[0].visual.origin,undefined);});

test('resolving ambiguous saved locations does not write until the selected pin is saved',async t=>{
 const {v}=fixture(t),note=savePlace(v,{name:'Unlocated café',category:'Café',location:'A broad area'}),before=v.read(note.path).content;
 const s=service(v,{provider:{geocode:async()=>[origin,{...origin,latitude:52,location:'Other area'}]}}),list=await s.command({action:'list'});
 const choices=await s.command({action:'resolve',id:list.results[0].id});assert.equal(choices.length,2);assert.equal(v.read(note.path).content,before);
 const update=await s.command({action:'save-location',id:choices[1].id});assert.match(v.read(note.path).content,/latitude: 52/);v.undo(update.change_id);assert.equal(v.read(note.path).content,before);
});

test('vault/config reset aborts an in-flight search before publishing old results',async t=>{
 const {v}=fixture(t);let release;const s=service(v,{provider:{geocode:()=>new Promise(resolve=>{release=resolve;})}});
 const pending=s.command({action:'search',query:'cafe',area:'Example'});s.clear();release([origin]);await assert.rejects(pending,/abort/i);
});
