const {test}=require('node:test'),assert=require('node:assert/strict');
const {createPlacesProvider,parseFeature,tileURL,categoryFor}=require('../src/places-provider.cjs');
const point={latitude:51.5,longitude:-.1};
const response=data=>({ok:true,text:async()=>JSON.stringify(data)});
test('provider translates café search, validates coordinates, uses pedestrian routes and finite times',async()=>{const calls=[];const p=createPlacesProvider({getKey:()=> 'fixture-key',fetchImpl:async url=>{calls.push(new URL(url));return response(url.pathname==='/v1/routing'?{features:[{properties:{time:480,distance:600}}]}:{features:[{properties:{name:'Example',formatted:'Example address',lat:51.51,lon:-.12}},{properties:{name:'Bad',lat:999,lon:0}}]});}});assert.equal((await p.search('quiet coffee shop',point,1500)).length,1);assert.equal(calls[0].searchParams.get('categories'),'catering.cafe');assert.equal(calls[0].searchParams.get('limit'),'15');assert.equal((await p.walkingRoute(point,{latitude:51.51,longitude:-.12})).seconds,480);assert.equal(calls[1].searchParams.get('mode'),'walk');assert.equal(calls[1].searchParams.get('waypoints'),'51.5,-0.1|51.51,-0.12');assert.equal(categoryFor('Café').label,'Café');assert.equal(parseFeature({properties:{lat:null,lon:null}}),null);});
test('credentials, quota errors, malformed responses and aborts never become places or times',async()=>{await assert.rejects(createPlacesProvider({getKey:()=>''}).search('cafe',point,1500),/Connect/);const quota=createPlacesProvider({getKey:()=> 'secret',fetchImpl:async()=>({ok:false,status:429})});await assert.rejects(quota.geocode('London'),/quota/);const malformed=createPlacesProvider({getKey:()=> 'secret',fetchImpl:async()=>response({features:[{properties:{time:'480'}}]})});await assert.rejects(malformed.walkingRoute(point,point),/unavailable/);const aborted=new AbortController();aborted.abort();await assert.rejects(malformed.geocode('London',{signal:aborted.signal}));});
test('map resource URLs are narrowly constrained and never accept arbitrary hosts or paths',()=>{assert.match(tileURL('orbplaces://tiles/positron/10/100/100.png','secret'),/^https:\/\/api.geoapify.com\/v1\/tile\/positron/);for(const url of ['https://evil.test/positron/10/1/1.png','orbplaces://other/positron/10/1/1.png','orbplaces://tiles/positron/2/99/0.png','orbplaces://tiles/positron/10/1/1.png?apiKey=other','orbplaces://tiles/../../settings'])assert.throws(()=>tileURL(url,'secret'));});

test('short-lived provider cache is bounded by expiry and key and does not leak mutable results',async()=>{
 let count=0,time=0,key='first';const p=createPlacesProvider({getKey:()=>key,now:()=>time,spacingMs:0,fetchImpl:async()=>{count++;return response({features:[{properties:{name:'Example',lat:0,lon:0}}]});}});
 const first=await p.geocode('Example');first[0].name='Changed';assert.equal((await p.geocode('Example'))[0].name,'Example');assert.equal(count,1);
 time=300001;await p.geocode('Example');assert.equal(count,2);key='second';await p.geocode('Example');assert.equal(count,3);p.clear();await p.geocode('Example');assert.equal(count,4);
});
