const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const {EventEmitter}=require('node:events'),{createRequire}=require('node:module'),{pathToFileURL}=require('node:url');
const {Vault,parseNote}=require('../src/vault.cjs');
const main=path.resolve(__dirname,'../src/main.cjs'),load=createRequire(main);
test('task completion IPC persists, rejects stale clicks, and supports Activity undo without an AI key',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orb-completion-ipc-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 const root=path.join(dir,'vault'),userData=path.join(dir,'app');fs.mkdirSync(userData);
 for(const name of ['Life Tasks','Business Tasks'])fs.mkdirSync(path.join(root,'0. Home',name),{recursive:true});
 const vault=new Vault(root,path.join(dir,'test-state'),{rulesPath:'',goalsFolder:'',habitFolder:''}),task=vault.createTask({title:'Draft proposal',list:'business',estimated_minutes:60});
 fs.writeFileSync(path.join(userData,'settings.json'),JSON.stringify({vaultPath:root,rulesPath:'',goalsFolder:'',habitFolder:''}));
 const handlers=new Map(),webContents=Object.assign(new EventEmitter(),{setWindowOpenHandler(){},send(){}});let ready;
 const app=Object.assign(new EventEmitter(),{getPath:()=>userData,requestSingleInstanceLock:()=>true,whenReady:()=>({then:fn=>{ready=Promise.resolve().then(fn);}})});
 const electron={app,protocol:{registerSchemesAsPrivileged(){},handle(){}},powerMonitor:new EventEmitter(),ipcMain:{handle:(n,fn)=>handlers.set(n,fn)},BrowserWindow:class extends EventEmitter{constructor(){super();this.webContents=webContents;}setVisibleOnAllWorkspaces(){}loadFile(){}},Tray:class extends EventEmitter{setToolTip(){}},nativeImage:{createFromPath:()=>({setTemplateImage(){}})},Menu:{buildFromTemplate:x=>x,setApplicationMenu(){}},globalShortcut:{register(){}},session:{defaultSession:{setPermissionRequestHandler(){},setPermissionCheckHandler(){}}},dialog:{showErrorBox:(_title,message)=>assert.fail(message)},safeStorage:{isEncryptionAvailable:()=>true}};
 const requireMock=name=>name==='electron'?electron:name.endsWith('orb-shortcut.node')?{start:()=>true,status:()=>({})}:name==='./trading212-service.cjs'?{createTradingService:()=>({start(){},resume(){}})}:load(name);
 vm.runInNewContext(fs.readFileSync(main,'utf8'),{require:requireMock,__dirname:path.dirname(main),Buffer,AbortController,process,setTimeout,clearTimeout,setInterval:()=>({unref(){}}),console},{filename:main});await ready;
 const handler=handlers.get('complete-task');assert.equal(typeof handler,'function');
 const event={sender:webContents,senderFrame:{url:pathToFileURL(path.join(path.dirname(main),'index.html')).href}};
 await assert.rejects(handler({}, {path:task.path,version:task.version}),/Untrusted/);
 const result=await handler(event,{path:task.path,version:task.version,planned:'2040-01-01'});
 const completed=parseNote(vault.read(task.path).content).data;
 assert.equal(completed.completed,true);assert.equal(completed.estimated_minutes,60);assert.notEqual(completed.planned,'2040-01-01');
 assert.ok(result.change_id);
 await assert.rejects(handler(event,{path:task.path,version:task.version}),/changed/);
 await handlers.get('undo')(event,result.change_id);
 assert.equal(parseNote(vault.read(task.path).content).data.completed,false);
 const recurring=vault.createTask({title:'Daily review',list:'life',planned:'2026-09-07',recurrence:{version:1,mode:'fixed',unit:'day',interval:1,weekdays:[],date_field:'planned',anchor:'2026-09-07',occurrence:'2026-09-07'}});
 await handler(event,{path:recurring.path,version:recurring.version});
 const next=parseNote(vault.read(recurring.path).content).data;
 assert.equal(next.completed,false);assert.ok(next.planned>'2026-09-07');assert.ok(next.recurrence_history.length);
 await assert.rejects(handler(event,{path:recurring.path,version:recurring.version}),/changed/);
});
