(() => {
 const make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
 const button=(label,fn)=>{const b=make('button','secondary',label);b.type='button';b.onclick=fn;return b;};
 const numeric=n=>typeof n==='number'&&Number.isFinite(n);
 const amount=(n,c)=>{if(!numeric(n))return '—';if(c==='GBX')return n.toLocaleString('en-GB',{maximumFractionDigits:2})+' GBX';try{return new Intl.NumberFormat('en-GB',{style:'currency',currency:c,maximumFractionDigits:2}).format(n);}catch{return n.toLocaleString('en-GB',{maximumFractionDigits:2})+' '+(c||'(currency unavailable)');}};
 const qty=n=>numeric(n)?n.toLocaleString('en-GB',{maximumFractionDigits:6}):'—';
 const pct=n=>numeric(n)?`${n>0?'+':''}${n.toFixed(2)}%`:'—';
 const date=d=>d&&!Number.isNaN(Date.parse(d))?new Date(d).toLocaleDateString('en-GB'):'—';
 const stamp=d=>d&&!Number.isNaN(Date.parse(d))?new Date(d).toLocaleString('en-GB'):'Not yet collected';
 const name=i=>i?.name||i?.ticker||'Unknown instrument';
 const clean=e=>e.message.replace(/^Error invoking remote method '[^']+': Error: /,'');
 const periods=[['today','Today'],['week','1W · 7 days'],['month','1M · 30 days'],['quarter','3M · 90 days'],['ytd','YTD'],['year','1Y · 365 days'],['tracking','Since tracking began'],['calendar_month','This calendar month'],['calendar_year','Calendar year'],['tax_year','UK tax year'],['custom','Custom dates']];
 function table(columns,rows){const wrap=make('div','table-scroll'),t=make('table'),head=make('thead'),hr=make('tr'),body=make('tbody');for(const c of columns){const th=make('th',null,c);th.scope='col';hr.append(th);}head.append(hr);for(const row of rows){const tr=make('tr');for(const cell of row){const td=make('td');if(cell instanceof Node)td.append(cell);else{td.textContent=cell??'—';td.title=String(cell??'');}tr.append(td);}body.append(tr);}t.append(head,body);wrap.append(t);return wrap;}
 function note(root,text){root.append(make('p','t212-note',text));}
 function metric(root,label,value){const box=make('div','t212-metric');box.append(make('span',null,label),make('strong',null,value));root.append(box);}
 function selectControl(label,choices,value,change){const wrap=make('label','t212-filter',label),s=make('select');s.setAttribute('aria-label',label);s.dataset.control=label;for(const [id,text]of choices)s.append(new Option(text,id));s.value=value;s.onchange=()=>change(s.value);wrap.append(s);return wrap;}
 function allocations(root,holdings,accountValue){
  const currencies=[...new Set(holdings.map(h=>h.walletImpact?.currency))];if(currencies.length!==1||!currencies[0]||holdings.some(h=>!numeric(h.walletImpact?.currentValue)||h.walletImpact.currentValue<0)){note(root,'Allocation unavailable: holding values or currencies are missing.');return;}
  const invested=holdings.reduce((sum,h)=>sum+h.walletImpact.currentValue,0),total=accountValue??invested;if(!(total>0)||total<invested-.02)return;const box=make('section','t212-allocation');box.append(make('h2',null,'Allocation'));note(box,accountValue?'Share of whole account · includes cash':'Share of invested value · excludes cash');
  const rows=holdings.map(h=>({name:name(h.instrument),value:h.walletImpact.currentValue}));if(accountValue)rows.push({name:'Cash',value:Math.max(0,total-invested)});
  for(const h of rows.sort((a,b)=>b.value-a.value).slice(0,8)){const share=h.value/total*100,row=make('div','t212-allocation-row'),label=make('div'),bar=make('progress');bar.max=100;bar.value=share;bar.setAttribute('aria-label',`${h.name} ${share.toFixed(1)}%`);label.append(make('span',null,h.name),make('strong',null,share.toFixed(1)+'%'));row.append(label,bar);box.append(row);}if(rows.length>8)note(box,'Largest 8 shown; denominator includes all holdings.');root.append(box);
 }
 function showMetric(root,m){if(!m)return;const section=make('section','t212-result');section.append(make('h2',null,m.metric==='account_performance'?'Period investment return':m.metric.replaceAll('_',' ')));note(section,`${m.status}${m.freshness?.stale?' · Stale observation':''}`);
  if(m.reason)note(section,m.reason);const cards=make('div','t212-metrics');if(m.metric==='account_performance'){metric(cards,'Gain / loss after external flows',amount(m.amount,m.currency));metric(cards,m.status==='estimated'?'Estimated return':'Return',pct(m.percentage));}else for(const t of m.totals||[])metric(cards,m.status==='partial'?'Loaded records only':'Total received / result',amount(t.amount,t.currency));section.append(cards);
  if(m.actual)note(section,`Observed ${stamp(m.actual.start)} → ${stamp(m.actual.end)}`);if(m.requested)note(section,`Reporting timezone: ${m.requested.timeZone}. Requested ${m.requested.start?stamp(m.requested.start):'start of tracking'} → ${stamp(m.requested.end)}.`);if(m.method)note(section,m.method);for(const w of m.warnings||[])note(section,w);
  if(m.groups?.length)section.append(table(['Group','Category','Amount'],m.groups.map(x=>[x.group,x.category,amount(x.amount,x.currency)])));
  if(m.evidence?.length){const details=make('details');details.append(make('summary',null,'Calculation evidence'));note(details,`Calculation version ${m.version}. Source: Trading 212. Export local history in Settings to inspect these record references.`);const code=make('pre','t212-evidence',m.evidence.join('\n'));details.append(code);section.append(details);}root.append(section);
 }
 function chart(root,series,currency,mode,funding=[]){const key=mode==='return'?'returnPercentage':'value',points=(series||[]).filter(p=>numeric(p[key]));if(!points.length){note(root,'No comparable chart observations yet.');return;}const width=660,height=180,margin=22,min=Math.min(...points.map(p=>p[key])),max=Math.max(...points.map(p=>p[key])),first=Date.parse(series[0].at),last=Date.parse(series.at(-1).at),ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',mode==='return'?'Observed investment return percentages; gaps are not interpolated':'Observed account values including deposits and withdrawals');svg.classList.add('t212-chart');
  const xy=p=>[(Date.parse(p.at)-first)/(last-first||1)*(width-margin*2)+margin,height-margin-(p[key]-min)/(max-min||1)*(height-margin*2)];let previous=null;for(const p of series){if(!numeric(p[key])){previous=null;continue;}const [x,y]=xy(p);if(previous&&Date.parse(p.at)-Date.parse(previous.at)<=10*60000){const [px,py]=xy(previous),line=document.createElementNS(ns,'line');for(const [k,v]of Object.entries({x1:px,y1:py,x2:x,y2:y}))line.setAttribute(k,v);svg.append(line);}const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',x);dot.setAttribute('cy',y);dot.setAttribute('r','3');const title=document.createElementNS(ns,'title');title.textContent=`${stamp(p.at)} · ${mode==='return'?pct(p[key]):amount(p[key],currency)}`;dot.append(title);svg.append(dot);previous=p;}for(const event of funding){if(Date.parse(event.at)<first||Date.parse(event.at)>last)continue;const x=(Date.parse(event.at)-first)/(last-first||1)*(width-margin*2)+margin,line=document.createElementNS(ns,'line');for(const [k,v]of Object.entries({x1:x,x2:x,y1:margin,y2:height-margin}))line.setAttribute(k,v);line.classList.add('t212-funding');const title=document.createElementNS(ns,'title');title.textContent=`${event.type} · ${stamp(event.at)} · ${amount(event.amount,event.currency)}`;line.append(title);svg.append(line);}root.append(svg);note(root,`${stamp(series[0].at)} → ${stamp(series.at(-1).at)} · ${mode==='return'?'Return excludes classified external funding':'Account value includes deposits and withdrawals'}. Gaps over 10 minutes are not joined.`);
  const details=make('details');details.append(make('summary',null,'Show chart data'));details.append(table(['Observed','Account value','Period return','Method state'],series.map(p=>[stamp(p.at),amount(p.value,currency),pct(p.returnPercentage),p.status])));root.append(details);
 }
 function render(host,initial,actions={}){
  host.replaceChildren();const root=make('section','t212-panel');host.append(root);let data=initial,loading=false,sequence=0,error=null,saved=!!actions.saved,search='',sort='value',selected=null,allocation='invested',chartMode='value',period=initial.query?.period||'today',metricName=initial.query?.metric||'income',groupBy=initial.query?.groupBy||'category',start=initial.query?.start||'',end=initial.query?.end||'',instrumentFilter=initial.query?.instrument||null,eventType='all',currencyFilter='all';
  const historyKeys=new Set();
  async function load(view,nextPagePath=null,extra={}){const token=++sequence;loading=true;error=null;draw();try{if(saved&&!data.accountKey)throw new Error('This older saved card has no verified account identity. Open Trading 212 from Explore for the current account.');const next=await actions.trading212({view,nextPagePath,connectionId:nextPagePath?data.connectionId:null,accountKey:data.accountKey||null,...extra});if(token!==sequence||!host.contains(root))return;
    if(nextPagePath){if(historyKeys.has(nextPagePath))throw new Error('This page was already loaded.');historyKeys.add(nextPagePath);const rows=[...(data.items||[]),...(next.items||[])],dedup=new Map();for(const row of rows){const id=row.reference||row.fill?.id||JSON.stringify(row);dedup.set(id,row);}data={...next,items:[...dedup.values()],fromStart:data.fromStart,complete:data.fromStart!==false&&!next.nextPagePath};}else{data=next;historyKeys.clear();}saved=false;
   }catch(e){if(token===sequence)error=clean(e);}finally{if(token===sequence){loading=false;draw();}}}
  function query(view='performance'){return load(view,null,{metric:view==='performance'?'account_performance':metricName,period,start:start||null,end:end||null,groupBy,instrument:selected?.instrument?.ticker||instrumentFilter||null});}
  function draw(){
   const focused=root.contains(document.activeElement)?document.activeElement.dataset.control:null,selection=document.activeElement?.selectionStart;
   root.replaceChildren();const header=make('header','t212-heading'),titles=make('div');titles.append(make('h1',null,'Trading 212'),make('p','t212-note',`${data.preview?'Fictional preview · ':''}${data.environment==='demo'?'Demo':'Live'} · Read-only${saved?' · Saved snapshot':''}`));header.append(titles,button('Settings',()=>actions.settings?.()));if(!data.setup&&!data.loading)header.append(button(loading?'Loading…':saved?'Refresh live':'Refresh',()=>['performance','query'].includes(data.view)?query(data.view):load(data.view,null,data.view==='instrument'?{instrument:data.position?.instrument?.ticker}:{})));root.append(header);
   if(error){const p=make('p','t212-error',error);p.setAttribute('role','alert');root.append(p);}if(data.loading){note(root,'Connecting to Trading 212…');return;}if(data.setup){note(root,data.setup);return;}
   const nav=make('nav','t212-tabs');nav.setAttribute('aria-label','Trading 212 views');for(const [id,label]of [['overview','Overview'],['holdings','Holdings'],['performance','Performance'],['query','Income'],['activity','Activity']]){const isSelected=id==='activity'?['trades','cash','pending'].includes(data.view):id===data.view||id==='holdings'&&data.view==='instrument'||id==='query'&&data.view==='dividends',b=button(label,()=>{selected=null;instrumentFilter=null;if(id==='performance'||id==='query'){metricName='income';query(id);}else load(id==='activity'?'trades':id);});b.setAttribute('aria-pressed',String(isSelected));nav.append(b);}root.append(nav);
   note(root,`Fetched ${stamp(data.updatedAt)}${data.cached?' · API cache':''}`);for(const warning of data.warnings||[])root.append(make('p','t212-error',warning));
   if(data.view==='overview'){
    const s=data.summary;if(s){const cards=make('div','t212-metrics');for(const [label,value]of [['Account value',s.totalValue],['Available cash',s.cash?.availableToTrade],['Invested value',s.investments?.currentValue],['Cost of open holdings',s.investments?.totalCost],['Unrealised gain · since purchase',s.investments?.unrealizedProfitLoss],['Realised gain · all time',s.investments?.realizedProfitLoss]])metric(cards,label,amount(value,s.currency));metric(cards,'Open holdings · since purchase',pct(data.unrealised?.percentage));root.append(cards);note(root,`Cash reserved: ${amount(s.cash?.reservedForOrders,s.currency)} · Cash in Pies: ${amount(s.cash?.inPies,s.currency)}`);note(root,`Account fetched ${stamp(data.summaryUpdatedAt||data.updatedAt)} · Holdings fetched ${stamp(data.holdingsUpdatedAt)}`);}
    showMetric(root,data.performance);root.append(button('View performance history',()=>query('performance')));
    if(data.holdings?.length){root.append(selectControl('Allocation basis',[['invested','Investments only'],['account','Whole account including cash']],allocation,v=>{allocation=v;draw();}));allocations(root,data.holdings,allocation==='account'?s?.totalValue:null);}
   }else if(data.view==='performance'||data.view==='query'){
    const filters=make('div','t212-filters');filters.append(selectControl('Period',periods,period,v=>{period=v;draw();if(v!=='custom')query(data.view);}));
    if(data.view==='query'){filters.append(selectControl('Metric',[['income','All paid income'],['dividends','Paid distributions'],['deposits','Deposits'],['net_contributions','Net cash contributions'],['realised_result','Realised trading result']],metricName,v=>{metricName=v;query('query');}),selectControl('Group by',[['category','Category'],['month','Month'],['instrument','Holding']],groupBy,v=>{groupBy=v;query('query');}));}
    if(period==='custom')for(const [label,value,set]of [['Start date',start,v=>start=v],['End date',end,v=>end=v]]){const l=make('label','t212-filter',label),input=make('input');input.type='date';input.value=value;input.setAttribute('aria-label',label);input.onchange=()=>set(input.value);l.append(input);filters.append(l);}if(period==='custom')filters.append(button('Apply dates',()=>query(data.view)));root.append(filters);
    showMetric(root,data.metric);if(data.view==='performance'){root.append(selectControl('Chart',[['value','Account value'],['return','Investment return %']],chartMode,v=>{chartMode=v;draw();}));chart(root,data.series,data.metric?.currency,chartMode,data.fundingEvents);if(data.fundingEvents?.length){const d=make('details');d.append(make('summary',null,'Funding events'),table(['When','Type','Amount'],data.fundingEvents.map(e=>[stamp(e.at),e.type,amount(e.amount,e.currency)])));root.append(d);if(data.fundingEventsTruncated)note(root,'Latest 100 funding markers shown; calculation includes all classified flows.');}if(data.seriesSampled)note(root,'Chart is sampled; export local history for every observation.');}else root.append(button('Browse broker payment records',()=>load('dividends')));
   }else if(data.view==='instrument'){
    const h=data.position;root.append(make('h2',null,name(h?.instrument)));if(h){note(root,`${h.instrument?.ticker} · ISIN ${h.instrument?.isin||'unavailable'}`);root.append(table(['Measure','Value'],[['Shares',qty(h.quantity)],['Current price',amount(h.currentPrice,h.instrument?.currency)],['Average paid',amount(h.averagePricePaid,h.instrument?.currency)],['Account value',amount(h.walletImpact?.currentValue,h.walletImpact?.currency)],['Cost',amount(h.walletImpact?.totalCost,h.walletImpact?.currency)],['FX impact · since purchase',amount(h.walletImpact?.fxImpact,h.walletImpact?.currency)]]));}
    root.append(button('Paid income for this holding',()=>{metricName='income';period='calendar_year';query('query');}));note(root,'Recorded share prices from the most recent 200 local holding observations (up to 90 days). No external price history.');if(data.prices?.length)root.append(table(['Observed','Price'],data.prices.map(p=>[stamp(p.at),amount(p.price,p.currency)])));else note(root,'No recorded prices yet. Enable tracking in Settings.');
    note(root,'Latest 100 locally loaded fills for this holding. Full-period results require complete history.');if(data.trades?.length)root.append(table(['Filled','Side / type','Shares','Net value'],data.trades.map(e=>[stamp(e.at),[e.source.order?.side,e.source.fill?.type].filter(Boolean).join(' · '),qty(e.source.fill?.quantity),amount(e.source.fill?.walletImpact?.netValue,e.source.fill?.walletImpact?.currency)])));
   }else if(data.view==='holdings'){
    const all=data.items||[],controls=make('div','t212-filters'),input=make('input');input.type='search';input.placeholder='Search holdings';input.setAttribute('aria-label','Search holdings');input.dataset.control='holdings-search';input.value=search;input.oninput=()=>{search=input.value;draw();};controls.append(input,selectControl('Sort holdings',[['value','Largest value'],['gain','Largest gain'],['loss','Largest loss'],['percentage','Return %'],['name','Name']],sort,v=>{sort=v;draw();}));root.append(controls);
    const total=all.reduce((sum,h)=>sum+(h.walletImpact?.currentValue||0),0),items=all.filter(h=>[name(h.instrument),h.instrument?.ticker,h.instrument?.isin].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='name'?name(a.instrument).localeCompare(name(b.instrument)):sort==='loss'?(a.walletImpact?.unrealizedProfitLoss??Infinity)-(b.walletImpact?.unrealizedProfitLoss??Infinity):sort==='gain'?(b.walletImpact?.unrealizedProfitLoss??-Infinity)-(a.walletImpact?.unrealizedProfitLoss??-Infinity):sort==='percentage'?(b.returnPercentage??-Infinity)-(a.returnPercentage??-Infinity):(b.walletImpact?.currentValue||0)-(a.walletImpact?.currentValue||0));
    if(!items.length)note(root,'No matching holdings.');else root.append(table(['Holding','Ticker','Shares','Value','Since purchase','Return %','Weight'],items.map(h=>[button(name(h.instrument),()=>{selected=h;instrumentFilter=h.instrument?.ticker;load('instrument',null,{instrument:instrumentFilter});}),h.instrument?.ticker,qty(h.quantity),amount(h.walletImpact?.currentValue,h.walletImpact?.currency),amount(h.walletImpact?.unrealizedProfitLoss,h.walletImpact?.currency),pct(h.returnPercentage),numeric(h.weightPercentage)?h.weightPercentage.toFixed(2)+'%':'—'])));
    note(root,'Weights use all loaded investments, excluding cash. Returns are since purchase, not daily changes.');
    if(selected){const h=selected,box=make('section','t212-detail');box.append(make('h2',null,name(h.instrument)));note(box,`${h.instrument?.ticker||'No ticker'} · ISIN ${h.instrument?.isin||'unavailable'}`);box.append(table(['Measure','Value'],[['Shares',qty(h.quantity)],['Current share price',amount(h.currentPrice,h.instrument?.currency)],['Average price paid',amount(h.averagePricePaid,h.instrument?.currency)],['Cost in account currency',amount(h.walletImpact?.totalCost,h.walletImpact?.currency)],['FX impact · since purchase',amount(h.walletImpact?.fxImpact,h.walletImpact?.currency)]]));box.append(button('Paid income for this holding',()=>{metricName='income';period='calendar_year';query('query');}),button('Show trades',()=>{search=h.instrument?.ticker||name(h.instrument);load('trades');}));root.append(box);}
   }else{
    if(['trades','cash','pending'].includes(data.view)){const sub=make('nav','t212-tabs');for(const [id,label]of [['trades','Trades'],['cash','Cash movements'],['pending','Pending orders']])sub.append(button(label,()=>{eventType='all';load(id);}));root.append(sub);}
    const rows=data.items||[],controls=make('div','t212-filters'),input=make('input');input.type='search';input.placeholder='Filter loaded records';input.setAttribute('aria-label','Filter loaded records');input.dataset.control='activity-search';input.value=search;input.oninput=()=>{search=input.value;draw();};controls.append(input);const types=[...new Set(rows.map(x=>x.fill?.type||x.type).filter(Boolean))];controls.append(selectControl('Event type',[['all','All types'],...types.map(t=>[t,t.replaceAll('_',' ')])],eventType,v=>{eventType=v;draw();}));for(const [label,value,set]of [['From',start,v=>start=v],['To',end,v=>end=v]]){const l=make('label','t212-filter',label),i=make('input');i.type='date';i.setAttribute('aria-label',label);i.value=value;i.onchange=()=>{set(i.value);draw();};l.append(i);controls.append(l);}root.append(controls);
    const currencies=[...new Set(rows.map(x=>x.currency||x.fill?.walletImpact?.currency||x.instrument?.currency).filter(Boolean))];controls.append(selectControl('Currency',[['all','All currencies'],...currencies.map(c=>[c,c])],currencyFilter,v=>{currencyFilter=v;draw();}));
    const filtered=rows.filter(x=>{const at=(x.paidOn||x.dateTime||x.fill?.filledAt||x.createdAt||'').slice(0,10);return (currencyFilter==='all'||(x.currency||x.fill?.walletImpact?.currency||x.instrument?.currency)===currencyFilter)&&(!start||at>=start)&&(!end||at<=end)&&(eventType==='all'||(x.fill?.type||x.type)===eventType)&&JSON.stringify(x).toLowerCase().includes(search.toLowerCase());});
    if(!filtered.length)note(root,'No matching records in this loaded history.');
    else if(data.view==='dividends')root.append(table(['Paid','Holding','Type','Amount'],filtered.map(x=>[date(x.paidOn),name(x.instrument)||x.ticker,x.type,amount(x.amount,x.currency)])));
    else if(data.view==='cash')root.append(table(['Date','Type','Amount'],filtered.map(x=>[date(x.dateTime),x.type?.replaceAll('_',' '),amount(x.amount,x.currency)])));
    else if(data.view==='trades')root.append(table(['Date','Holding','Side / event','Shares','Price','Net value','Realised'],filtered.map(x=>[date(x.fill?.filledAt),name(x.order?.instrument),[x.order?.side,x.fill?.type].filter(Boolean).join(' · '),qty(x.fill?.quantity),amount(x.fill?.price,x.order?.instrument?.currency),amount(x.fill?.walletImpact?.netValue,x.fill?.walletImpact?.currency),amount(x.fill?.walletImpact?.realisedProfitLoss,x.fill?.walletImpact?.currency)])));
    else root.append(table(['Created','Holding','Side','Status','Shares / value','Limit','Stop'],filtered.map(x=>[date(x.createdAt),name(x.instrument),x.side,x.status,x.strategy==='VALUE'?amount(x.value,x.currency):qty(x.quantity),amount(x.limitPrice,x.instrument?.currency),amount(x.stopPrice,x.instrument?.currency)])));
    if(data.view!=='pending'){note(root,`${rows.length} records loaded. ${data.nextPagePath?'More pages available; filters apply to loaded records only.':data.fromStart===false?'Partial history page. Refresh to start at the latest records.':'All available pages loaded.'}`);if(data.nextPagePath)root.append(button('Load older records',()=>load(data.view,data.nextPagePath)));}
   }
   if(actions.request)root.append(button('Ask Smith about my investments',()=>actions.request('Review my Trading 212 portfolio. Use the computed performance and income metrics, and explain any missing history.')));root.setAttribute('aria-busy',String(loading));if(loading)note(root,'Loading… You can switch views while this request finishes.');
   if(focused){const el=[...root.querySelectorAll('[data-control]')].find(e=>e.dataset.control===focused);el?.focus();if(typeof selection==='number'&&el?.type==='search')el.setSelectionRange(selection,selection);}
  }
  draw();const timer=setInterval(()=>{if(!host.contains(root)){clearInterval(timer);return;}if(!saved&&!loading&&(period!=='custom'||start&&end)&&!document.hidden&&root.getClientRects().length&&['overview','performance','query'].includes(data.view))['performance','query'].includes(data.view)?query(data.view):load(data.view);},60000);
 }
 async function open(){const loading={kind:'trading212',view:'overview',environment:settings?.trading212?.environment||'live',loading:true};displayVisual(loading);try{const result=await api.trading212({view:'overview'});if(currentVisual===loading&&cardMode==='visual')displayVisual(result);}catch(e){if(currentVisual===loading&&cardMode==='visual')displayVisual({...loading,loading:false,setup:clean(e)});}}
 let connectionBusy=false;
 function clearSecrets(){document.getElementById('t212-key').value='';document.getElementById('t212-secret').value='';}
 function capabilities(values){const host=$('t212-capabilities');if(!host)return;host.replaceChildren();if(values)for(const [kind,value]of Object.entries(values)){const line=make('p','t212-note',`${value.permission}: ${value.state}${value.checkedAt?' · '+stamp(value.checkedAt):''}${value.message?' · '+value.message:''}`);host.append(line);}}
 async function tracking(action='status',accountKey=null){const message=$('t212-tracking-message');try{if(action==='delete'&&!confirm('Delete this local investment history? Tracking will stop. Saved chats, notes and broker data will remain.'))return;const r=await api.trading212Tracking({action,accountKey,timeZone:$('t212-timezone').value});message.textContent=r.error||`${r.enabled?'Tracking while Orb runs':'Tracking off / paused'} · Last capture ${stamp(r.lastCapture)} · ${r.records||0} local records · ${((r.bytes||0)/1048576).toFixed(1)} MB store${r.exported?' · Export saved':''}`;if(r.timeZone)$('t212-timezone').value=r.timeZone;const host=$('t212-history-status');host.replaceChildren();for(const [kind,c]of Object.entries(r.coverage||{}))note(host,`${kind}: ${c.complete?'history loaded':'backfilling'} · ${c.pages||0} pages · verified through ${stamp(c.through)}${c.error?' · '+c.error:''}`);for(const account of r.accounts||[]){const row=make('div','t212-actions');row.append(make('span',null,`${account.environment} · ${account.currency} · started ${date(account.createdAt)}`),button('Export JSON',()=>tracking('export',account.accountKey)),button('Delete history',()=>tracking('delete',account.accountKey)));host.append(row);}capabilities(r.capabilities);}catch(e){message.textContent=clean(e);}}
 function loadSettings(){clearSecrets();const c=settings?.trading212||{configured:false,environment:'live'};$('t212-environment').value=c.environment;$('t212-status').textContent=c.configured?'Saved · '+(c.environment==='demo'?'Demo':'Live'):'Set up';$('t212-status').className='integration-status'+(c.configured?' connected':'');$('t212-key').placeholder=c.configured?'Key saved · leave blank to keep':'API key';$('t212-secret').placeholder=c.configured?'Secret saved · leave blank to keep':'API secret';$('t212-disconnect').hidden=!c.configured;$('t212-message').textContent='';tracking();}
 async function connect(action){if(connectionBusy)return;connectionBusy=true;const fields=[...$('trading212-integration').querySelectorAll('input,select,button')];fields.forEach(x=>x.disabled=true);$('t212-message').textContent=action==='disconnect'?'Disconnecting…':'Checking each read capability…';try{const r=await api.trading212Connect({action,environment:$('t212-environment').value,key:$('t212-key').value.trim(),secret:$('t212-secret').value.trim()});if(action!=='test'){settings.trading212=r.trading212;loadSettings();if(currentVisual?.kind==='trading212'){currentVisual=null;$('visual-view').replaceChildren();}}capabilities(r.capabilities);const partial=Object.values(r.capabilities||{}).some(x=>x.state!=='available');$('t212-message').textContent=action==='disconnect'?'Disconnected. Credentials removed; local history is retained until deleted below.':`${action==='test'?'Checked':'Saved'} · ${r.currency}${partial?' · Some capabilities need attention':''}. ${action==='test'?'Connect & save to store these credentials.':''}`;}catch(e){$('t212-message').textContent=clean(e);}finally{connectionBusy=false;fields.forEach(x=>x.disabled=false);}}
 function init(){for(const action of ['test','save','disconnect'])$('t212-'+action).onclick=()=>connect(action);for(const action of ['enable','pause','rescan','status'])$('t212-track-'+action).onclick=()=>tracking(action);if(preview)installPreview();}
 function installPreview(){
  api.trading212Connect=async()=>{throw new Error('Connect in the Mac app. This preview uses fictional data.');};
  api.trading212Tracking=async()=>({enabled:false,timeZone:'Europe/London',accounts:[],error:'Fictional preview · tracking and exports require the Mac app.'});
  api.trading212=async({view='overview',period='today',metric:metricName='income',nextPagePath=null,instrument=null,start:customStart=null,end:customEnd=null}={})=>{
   const holding=(ticker,name,quantity,value,cost,price,currency='USD')=>({instrument:{ticker,name,currency,isin:'EXAMPLE00000'},quantity,averagePricePaid:price*.9,currentPrice:price,returnPercentage:(value-cost)/cost*100,weightPercentage:value/8000*100,walletImpact:{currency:'GBP',currentValue:value,totalCost:cost,unrealizedProfitLoss:value-cost,fxImpact:12}}),holdings=[holding('ALPHA_US_EQ','Alpha Technologies',12,2400,2000,260),holding('WORLD_EQ','Global Equity ETF',40,4200,3800,105,'GBP'),holding('GREEN_EQ','Green Energy Fund',20,1400,1600,70,'GBP')],now=Date.now(),at=new Date(now).toISOString();
   const base={schemaVersion:2,accountKey:'fictional-preview',connectionId:'fictional-preview',fromStart:!nextPagePath,kind:'trading212',view,environment:'demo',preview:true,updatedAt:at,warnings:[],nextPagePath:null};
   const opening=new Date(now);opening.setHours(0,0,0,0);if(['week','month','quarter','year'].includes(period))opening.setDate(opening.getDate()-{week:7,month:30,quarter:90,year:365}[period]);if(period==='calendar_month')opening.setDate(1);if(['ytd','calendar_year'].includes(period))opening.setMonth(0,1);if(period==='tax_year'){const y=opening.getFullYear()-(opening.getMonth()<3||opening.getMonth()===3&&opening.getDate()<6?1:0);opening.setFullYear(y,3,6);}if(period==='tracking')opening.setTime(now-3600000);if(period==='custom'&&customStart)opening.setTime(new Date(customStart+'T00:00:00').getTime());const openingAt=opening.toISOString(),previewZone=Intl.DateTimeFormat().resolvedOptions().timeZone;
   const m={version:1,metric:'account_performance',status:'estimated',amount:68,percentage:.74,currency:'GBP',actual:{start:openingAt,end:at},requested:{start:openingAt,end:at,timeZone:previewZone},method:'Fictional Modified Dietz estimate',freshness:{asOf:at,stale:false},evidence:['fictional-start','fictional-end'],warnings:['Fictional data. Actual dates and coverage determine available periods.']};
   if(view==='overview')return {...base,summaryUpdatedAt:at,holdingsUpdatedAt:at,summary:{currency:'GBP',totalValue:9200,cash:{availableToTrade:1000,inPies:100,reservedForOrders:100},investments:{currentValue:8000,totalCost:7400,unrealizedProfitLoss:600,realizedProfitLoss:240}},unrealised:{percentage:600/7400*100},performance:m,holdings};
   if(view==='instrument')return {...base,position:holdings.find(h=>h.instrument.ticker===instrument)||holdings[0],prices:[{at,price:260,currency:'USD'}],trades:[],query:{instrument}};if(view==='holdings')return {...base,items:holdings};if(view==='performance')return {...base,metric:m,query:{period,metric:'account_performance'},series:Array.from({length:13},(_,i)=>({at:new Date(now-(12-i)*300000).toISOString(),value:9132+i*5.67,returnPercentage:i*.0617,status:'estimated'}))};
   if(view==='query')return {...base,query:{period,metric:metricName},metric:{...m,metric:metricName,status:'available',amount:45.21,percentage:null,totals:[{currency:'GBP',amount:45.21}],groups:[{group:'Dividends',category:'Dividends',currency:'GBP',amount:42},{group:'Cash interest',category:'Cash interest',currency:'GBP',amount:3.21}],method:'Fictional paid-income totals'}};
   if(view==='dividends')return {...base,items:[{reference:nextPagePath?'older':'newer',paidOn:nextPagePath?'2025-12-10':'2026-09-10',instrument:holdings[1].instrument,type:'ORDINARY',amount:nextPagePath?32:42,currency:'GBP'}],nextPagePath:nextPagePath?null:'/api/v0/equity/history/dividends?limit=50&cursor=1'};
   if(view==='cash')return {...base,items:[{dateTime:'2026-09-01',type:'DEPOSIT',amount:500,currency:'GBP'},{dateTime:'2026-09-10',type:'INTEREST_ON_FREE_CASH',amount:3.21,currency:'GBP'}]};
   if(view==='trades')return {...base,items:[{order:{instrument:holdings[0].instrument,side:'BUY'},fill:{filledAt:'2026-09-04',quantity:2,price:250,type:'TRADE',walletImpact:{netValue:-384,currency:'GBP',realisedProfitLoss:0}}}]};return {...base,items:[]};
  };
 }
 window.trading212UI={render,open,loadSettings,clearSecrets,init};
})();
